name: tabnews
description: "Cliente para visualizar e interagir com as not√≠cias/artigos publicados no TabNews"

publish_to: "none"
homepage: https://softyes.com.br
repository: https://github.com/TabNewsNC/tabnewsnc_watch

version: 0.1.0+1

environment:
  sdk: ^3.10.3
  flutter: ^3.38.4

dependencies:
  flutter:
    sdk: flutter

  wear_plus: ^1.2.4
  rotary_scrollbar: ^1.1.0
  tabnewsnc_ui:
    path: ../tabnewsnc_ui
  tabnewsnc_engine:
    path: ../tabnewsnc_engine

dev_dependencies:
  flutter_test:
    sdk: flutter

  icons_launcher: ^3.0.3
  very_good_analysis: ^10.0.0
  flutter_native_splash: ^2.4.7
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
